name: CI/CD for Firebase Functions

on:
  pull_request:
    branches:
      - development

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Run tests
        run: npm test
        working-directory: ./functions

      - name: Firebase CLI setup
        uses: wzieba/Firebase-Action@v2
        with:
          args: ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        working-directory: ./functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
